[package]
name = "rust_box"
version = "0.1.0"
edition = "2024"

[dependencies]
rust_box_lib = { path = "lib" }
parser = { path = "parser" }
serverlib = {path = "serverlib"}

[workspace]
resolver = "2"
members = ["parser", "lib"]
